<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-03T20:54:17 EDT" name="Default Suite" finished-at="2024-05-03T20:54:55 EDT" duration-ms="38314">
    <groups>
    </groups>
    <test started-at="2024-05-03T20:54:17 EDT" name="merchantRateChecking" finished-at="2024-05-03T20:54:55 EDT" duration-ms="38314">
      <class name="Tests.seleniumTest">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Tests.seleniumTest@6fdbe764]" started-at="2024-05-03T20:54:17 EDT" name="beforeMethod" finished-at="2024-05-03T20:54:24 EDT" duration-ms="7442" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="Login()[pri:0, instance:Tests.seleniumTest@6fdbe764]" started-at="2024-05-03T20:54:24 EDT" name="Login" finished-at="2024-05-03T20:54:33 EDT" duration-ms="9373" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Tests.seleniumTest@6fdbe764]" started-at="2024-05-03T20:54:34 EDT" name="afterMethod" finished-at="2024-05-03T20:54:34 EDT" duration-ms="984" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Tests.seleniumTest@6fdbe764]" started-at="2024-05-03T20:54:34 EDT" name="beforeMethod" finished-at="2024-05-03T20:54:42 EDT" duration-ms="7336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="clickRateTab()[pri:0, instance:Tests.seleniumTest@6fdbe764]" started-at="2024-05-03T20:54:42 EDT" name="clickRateTab" finished-at="2024-05-03T20:54:54 EDT" duration-ms="12001" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sign in - Google Accounts] but found [FluzCms]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sign in - Google Accounts] but found [FluzCms]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at POM.cmsLogin.searchMerchantRate(cmsLogin.java:68)
at Tests.seleniumTest.clickRateTab(seleniumTest.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickRateTab -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Tests.seleniumTest@6fdbe764]" started-at="2024-05-03T20:54:54 EDT" name="afterMethod" finished-at="2024-05-03T20:54:55 EDT" duration-ms="1061" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- Tests.seleniumTest -->
    </test> <!-- merchantRateChecking -->
  </suite> <!-- Default Suite -->
</testng-results>
